# 绕着激光雷达的哪个轴旋转
# x 轴：[1, 0, 0]
# y 轴：[0, 1, 0] 以此类推
axis: [1, 0, 0]
# 原始数据文件夹
raw_dirname: data/rd2
# 组装后文件的名字
cmb_filename: slg_b.pcd
# 提取出来的特征的文件夹
obj_dirname: data/objs1
# 标定结果文件名
mat_file_name: cfg/mat.yaml
# 标定用的激光雷达是否为多线激光雷达
is_multi_line: true
# 优化步数
num_step: 1000
# 终止条件 - 误差
thd_err: 1e-100
# 终止条件 - 参数改变量
thd_chg: 1e-100
# 终止条件 - 梯度
thd_gdt: 1e-100
# 是否打印计算过程
is_print_progress: true
